name: Workflow Demo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: list the dir
      run: ls
    - name: Create a text file
      run: echo "Hello, world!" >> /artifacts/hello.txt

    - name: Archive text file
      uses: actions/upload-artifact@v7
      with:
        name: hello-artifact
        path: /artifacts/hello.txt
  
  download:
   needs: build
   runs-on: ubuntu-latest
   steps:
     - name: download the artifact
       uses: actions/download-artifact@v8
       with:
         name: hello-artifact
         # path: ./artifacts
         
     - name: read the file
       run: cat ./artifacts/hello.txt
         
